### ISSUE TITLE
fetchAndInstantiate instead of wasm2es6js?

### ISSUE THREAD

**Issue by adiba** [alexcrichton/wasm-bindgen#15] opened 2018-02-11 19:12 UTC
Why do we need `wasm2es6js` here?
Couldn't we just as well use the `fetch` function and instantiate a `WebAssembly` with the response?

**Comment by alexcrichton** [comment] 2018-02-11 19:40
A good question! The general idea is that a wasm file is just an ES6 module, but as it turns out there's not actually many tools that work like that! AFAIK bundlers don't yet have support for this where the wasm file can both import/export, so the wasm2es6js tool is basically just a hack for now.

It's worth pointing out though that wasm2es6js isn't required at all, so long as the wasm file is interpreted as an ES6 module everything should work out!

**Comment by adiba** [comment] 2018-02-11 20:18
Why does the WASM have to be encoded as string? We could just `fetch` the `.wasm`s. Are you aiming for a single js file?

**Comment by alexcrichton** [comment] 2018-02-11 20:52
Oh using `fetch` is fine but I wasn't sure how to integrate that with bundlers, there's also certainly no need to use base64! It was just worked for the time being.

**Comment by alexcrichton** [comment] 2018-02-13 23:54
I'm gonna close this for now as currently the tool is working as intended, but I'm hoping it'll be obviated by the work of bundlers soon!

**Closed by alexcrichton** 2018-02-13 23:54 UTC
