### ISSUE TITLE
Module not found: "env"

### ISSUE THREAD

**Issue by dflemstr** [alexcrichton/wasm-bindgen#21] opened 2018-02-12 23:12 UTC
When using `wasm2es6js` or even looking at the generated raw wasm file, the generated module refers to a module called `"env"`.  This module I assume should resolve to the main `.js` file generated by `wasm-bindgen` since it expects it to contain `__wbindgen_throw` according to the import table of the `.wasm` file.

However it also expects the `__web_on_grow` function which is not defined.

I'm attempting to integrate this tool with webpack.  How should I map this `"env"` module?

**Comment by alexcrichton** [comment] 2018-02-12 23:31
Thanks for the report! In general the `wasm2es6js` tool though expects the wasm module it's being run over to look like an ES6 module, meaning that imports look like JS `import` statements and such. The Rust compiler, however, has no way of configuring (right now) the module to import from, it's always `env`. The `wasm-bindgen` tool in this repository communicates metadata from the rust file to the tool itself to rewrite the imports, but other imports from rustc aren't rewritten as wasm-bindgen doesn't know about them.

I suspect this won't be usable over "general" ES module files, but rather a different strategy would be needed for loading the wasm file.

**Comment by alexcrichton** [comment] 2018-02-13 23:54
I'm going to close this as I think this is a general "ES modules in wasm are a little underbaked issue" but otherwise the tool I believe is working as intended

**Closed by alexcrichton** 2018-02-13 23:54 UTC
